# SPDX-FileCopyrightText: 2025 Iva Horn
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [
    "**/*.xml", 
    "**/*.png", 
    "**/*.pxd",
    "**/*.json",
    "Package.resolved",
    ".gitignore", 
    ".swiftformat", 
    ".swift-version",
    "Tests/RainmakerTests/Responses/**"
]
SPDX-FileCopyrightText = "2025 Iva Horn"
SPDX-License-Identifier = "MIT"
