// SPDX-FileCopyrightText: 2026 Iva Horn
// SPDX-License-Identifier: MIT

import Foundation

///
/// The image of a Nextcloud Talk conversation as the server resolved it.
///
/// This is what ``Server/conversationAvatar(_:darkTheme:)`` returns. The server decides which image a conversation has, so a client renders whatever comes back rather than deciding anything itself: it is a picture a moderator uploaded, an emoji picked in the web interface, the other person's avatar in a ``ConversationType/oneToOne`` conversation, or an icon the server generates from the kind of conversation it is.
///
/// > Important: The image is commonly an SVG document rather than a bitmap, because every generated icon and every emoji avatar is one. Anything turning these bytes into a platform image has to handle that, which is what ``contentType`` is for.
///
/// Whether the image was set by a user or generated by the server is deliberately not reported: the response carries no such signal, and the only field which does is the conversation's `isCustomAvatar`, which ``Conversation`` does not model.
///
public struct ConversationAvatar: Model {
    ///
    /// The bytes of the image exactly as the server sent them.
    ///
    public let data: Data

    ///
    /// The MIME type of ``data``, e.g. `"image/svg+xml"` or `"image/png"`.
    ///
    /// This is the response's `Content-Type` and the only description of what the bytes are, which is why ``Server/conversationAvatar(_:darkTheme:)`` treats its absence as a failure rather than guessing.
    ///
    public let contentType: String
}
